[package]
name = "buildy"
version = "0.0.7"
authors = ["Steve Mostovoy <stevemostovoysm@gmail.com>"]
edition = "2018"

categories = ["command-line-utilities", "concurrency", "development-tools", "development-tools::build-utils", "filesystem"]
documentation = "https://github.com/stovoy/buildy/blob/master/README.md"
description = "An ultra-fast parallel build system for local iteration"
homepage = "https://github.com/stovoy/buildy"
keywords = ["build", "parallel", "incremental", "watch", "tool"]
license = "MIT"
maintenance = { status = "actively-developed" }
readme = "README.md"
repository = "https://github.com/stovoy/buildy"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
crossbeam = "=0.7.2"
duct = "0.13.1"
walkdir = "2"
rust-crypto = "^0.2"
notify = { version = "=5.0.0-pre.1", features = ["serde"] }
